# Mod de traduccion al espanol para Banjo-Kazooie: Recompiled

[manifest]

id = "bk_spanish_translation"

version = "3.2.0"

display_name = "BK Spanish / Espanol"

description = """
Traduccion completa de Banjo-Kazooie al espanol. \
913+ dialogos traducidos, 9 mundos, Quiz Furnace Fun, cutscenes, menus. \
Incluye tildes visibles y signos invertidos. \
Compatible con BK Reloaded (HD textures) usando el .rtz incluido.
"""

short_description = "Traduccion completa al espanol de Banjo-Kazooie."

authors = [ "wilrojasdev" ]

game_id = "bk"

minimum_recomp_version = "1.0.1"

dependencies = [ "bk_recomp_asset_expansion_pak:0.0.3" ]

optional_dependencies = []

conflicts = []

native_libraries = []

[inputs]

elf_path = "build/mod.elf"

mod_filename = "bk_spanish_translation"

func_reference_syms_file = "BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]

additional_files = [
    "rt64.json",
    "fonts/excl_inv.png",
    "fonts/quest_inv.png",
    "fonts/A_acute.png",
    "fonts/E_acute.png",
    "fonts/I_acute.png",
    "fonts/N_tilde.png",
    "fonts/O_acute.png",
    "fonts/U_acute.png"
]
