# Mod de traduccion al espanol para Banjo-Kazooie: Recompiled

[manifest]

id = "bk_spanish_translation"

version = "0.1.0"

display_name = "BK Spanish / Espanol"

description = """
Traduce los dialogos de Banjo-Kazooie al espanol. \
Trabajo en progreso - se iran agregando traducciones por mundo gradualmente.
"""

short_description = "Traduccion al espanol de Banjo-Kazooie."

authors = [ "wilrojasdev" ]

game_id = "bk"

minimum_recomp_version = "1.0.1"

dependencies = [ "bk_recomp_asset_expansion_pak:0.0.3" ]

optional_dependencies = []

conflicts = []

native_libraries = []

[inputs]

elf_path = "build/mod.elf"

mod_filename = "bk_spanish_translation"

func_reference_syms_file = "BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]

additional_files = [
    "rt64.json",
    "fonts/Banjo-Kazooie#E6A5BFBF#3#2_all.png",
    "fonts/Banjo-Kazooie#6E2F0F7F#3#2_all.png",
    "fonts/Banjo-Kazooie#CD0854EE#3#2_all.png",
    "fonts/Banjo-Kazooie#074FAF6B#3#2_all.png",
    "fonts/Banjo-Kazooie#20B82E8E#3#2_all.png",
    "fonts/Banjo-Kazooie#D22E23E4#3#2_all.png",
    "fonts/Banjo-Kazooie#B8B7B0BF#3#2_all.png",
    "fonts/Banjo-Kazooie#A741919B#3#2_all.png"
]
